# -*- coding: utf-8 -*-
# Vertel Sverige AB AGPL-3

import json

from odoo import _, api, fields, models
from odoo.exceptions import UserError, ValidationError


class SocialMarketingPost(models.Model):
    """ Extends social_marketing.post (Vertel CE) with communication planning,
    policy linking, approval workflow and compliance validation. """

    _inherit = 'social_marketing.post'

    # Link to plan and policy
    plan_line_id = fields.Many2one('communication.plan.line',
        string='Plan Line', ondelete='set null', tracking=True,
        help="Link to the plan line in the communication plan.")
    plan_id = fields.Many2one(related='plan_line_id.plan_id',
        string='Plan', store=True)
    policy_id = fields.Many2one(related='plan_line_id.plan_id.policy_id',
        string='Policy', store=True)

    # Approval workflow
    approval_state = fields.Selection([
        ('draft', 'Draft'),
        ('pending_approval', 'Pending Approval'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
    ], string='Approval Status', default='draft', required=True, tracking=True)
    reviewer_id = fields.Many2one('res.users', string='Reviewer', tracking=True)
    rejection_reason = fields.Text('Rejection Reason',
        help="Reason why the post was rejected.")

    # Policy compliance
    compliance_check_passed = fields.Boolean('Compliance Check Passed', default=False)
    compliance_warnings = fields.Text('Compliance Warnings',
        help="Warnings from the policy compliance check.")

    # Deterministic compliance snapshot (publishing pipeline)
    compliance_snapshot = fields.Json(
        string='Compliance Snapshot',
        help='Deterministic compliance snapshot (policy version, verdict, '
             'warnings) recorded at compliance check time. Never overwritten.')
    compliance_checked_at = fields.Datetime(
        string='Compliance Checked At',
        help='Timestamp of the compliance snapshot.')
    needs_recheck = fields.Boolean(
        string='Needs Recheck', default=False,
        help='Set when the communication policy changes while the post is '
             'pending approval, awaiting customer approval, or approved but '
             'not yet completed.')
    compliance_recheck_verdict = fields.Selection(
        [('pass', 'Pass'), ('fail', 'Fail')],
        string='Recheck Verdict',
        help='Result of the last compliance re-check after a policy change.')

    # AI generation
    ai_generated = fields.Boolean('AI Generated', default=False,
        help="Content was generated by AI.")
    ai_prompt = fields.Text('AI Prompt',
        help="The prompt used for AI generation.")

    def action_submit_for_approval(self):
        """ Submit post for approval. Runs policy compliance check first. """
        self.ensure_one()
        if self.approval_state not in ('draft', 'rejected'):
            raise UserError(_('Only draft or rejected posts can be submitted for approval.'))

        # Run compliance check
        warnings = self._check_policy_compliance()
        if warnings:
            self.compliance_warnings = '\n'.join(warnings)
            self.compliance_check_passed = False
        else:
            self.compliance_warnings = False
            self.compliance_check_passed = True

        # Determine reviewer from policy.approval_chain
        self._assign_reviewer_from_policy()

        self.approval_state = 'pending_approval'

        # Publishing pipeline: log the stage + write the deterministic
        # compliance snapshot (written once, never overwritten).
        self._pipeline_log('submitted')
        self._write_compliance_snapshot()
        self._pipeline_log(
            'compliance_checked',
            result='pass' if self.compliance_check_passed else 'fail',
        )

        # Notify reviewer via activity
        if self.reviewer_id:
            self.activity_schedule(
                'mail.mail_activity_data_todo',
                user_id=self.reviewer_id.id,
                note=_('Please review and approve/reject the social media post '
                       '"%(post)s" for plan "%(plan)s".',
                       post=self.display_name, plan=self.plan_id.name)
            )
        # Notify creator via chatter
        self.message_post(
            body=_('Post submitted for approval. Reviewer: %(reviewer)s',
                   reviewer=self.reviewer_id.name if self.reviewer_id else 'Not assigned'),
            message_type='notification',
            subtype_xmlid='mail.mt_comment')

    def _assign_reviewer_from_policy(self):
        """ Assign reviewer based on policy.approval_chain JSON.
        Example approval_chain:
        [{"role": "creator", "action": "submit"},
         {"role": "approver", "action": "approve", "user_id": 3}]
        If user_id is specified, use it. Otherwise find first user with approver group. """
        self.ensure_one()
        if not self.policy_id or not self.policy_id.approval_chain:
            return

        try:
            chain = self.policy_id.approval_chain
            if isinstance(chain, str):
                chain = json.loads(chain)
        except (json.JSONDecodeError, TypeError):
            return

        if not isinstance(chain, list):
            return

        # Find the approver step
        for step in chain:
            if isinstance(step, dict) and step.get('role') == 'approver':
                if step.get('user_id'):
                    self.reviewer_id = step['user_id']
                    return
                # Otherwise find first user with approver group
                approver = self.env['res.users'].search([
                    ('groups_id', 'in', self.env.ref('social_planner.group_social_content_approver').id),
                    ('share', '=', False),
                ], limit=1)
                if approver:
                    self.reviewer_id = approver.id
                return

    def _write_compliance_snapshot(self):
        """ Record the deterministic compliance snapshot on the post.

        Written once, at compliance check time. The snapshot is the basis
        for the approval decision and is never overwritten afterwards. """
        self.ensure_one()
        if self.compliance_snapshot:
            return
        self.write({
            'compliance_snapshot': {
                'policy_version': self.policy_id.version if self.policy_id else False,
                'verdict': 'pass' if self.compliance_check_passed else 'fail',
                'warnings': self.compliance_warnings or [],
                'checked_at': fields.Datetime.now().isoformat(),
            },
            'compliance_checked_at': fields.Datetime.now(),
        })

    def _check_compliance_snapshot(self):
        """ Refuse approval unless a complete compliance snapshot exists.

        The snapshot is written once, when the post passes its compliance
        check. Approval must not be possible without it, otherwise the post
        says it was checked while carrying no record of what it was checked
        against — and the snapshot is the basis for the approval decision.

        Raises UserError naming what is missing. Used by every path that can
        put a post into an approved state (internal approval, customer
        approval), so no path can bypass the guarantee. """
        self.ensure_one()
        snapshot = self.compliance_snapshot
        if not snapshot:
            raise UserError(_(
                'Cannot approve %(post)s: it has no compliance snapshot.\n'
                'The post must be submitted for approval first, so that the '
                'policy compliance check runs and its result is recorded.',
                post=self.display_name))
        if not isinstance(snapshot, dict):
            raise UserError(_(
                'Cannot approve %(post)s: its compliance snapshot is not '
                'readable (expected an object, got %(kind)s).',
                post=self.display_name, kind=type(snapshot).__name__))
        missing = [
            key for key in ('policy_version', 'verdict', 'checked_at')
            if snapshot.get(key) in (None, False, '')
        ]
        if missing:
            raise UserError(_(
                'Cannot approve %(post)s: its compliance snapshot is '
                'incomplete (missing: %(missing)s).',
                post=self.display_name, missing=', '.join(missing)))
        return True

    def action_approve(self):
        """ Approve post — it can now be published. """
        self.ensure_one()
        if self.approval_state != 'pending_approval':
            raise UserError(_('Only posts pending approval can be approved.'))
        self._check_compliance_snapshot()
        self.approval_state = 'approved'
        self.message_post(
            body=_('Post approved by %(user)s.', user=self.env.user.name),
            message_type='notification',
            subtype_xmlid='mail.mt_comment')
        # Mark activity as done
        self.activity_feedback(['mail.mail_activity_data_todo'])
        # Publishing pipeline: log the approved stage.
        self._pipeline_log('approved')

    def action_reject(self, reason=False):
        """ Reject post — back to draft with comment. """
        self.ensure_one()
        if self.approval_state != 'pending_approval':
            raise UserError(_('Only posts pending approval can be rejected.'))
        self.approval_state = 'rejected'
        if reason:
            self.rejection_reason = reason
        self.message_post(
            body=_('Post rejected by %(user)s. Reason: %(reason)s',
                   user=self.env.user.name,
                   reason=self.rejection_reason or 'No reason provided'),
            message_type='notification',
            subtype_xmlid='mail.mt_comment',
            partner_ids=[self.create_uid.partner_id.id])
        # Mark activity as done
        self.activity_feedback(['mail.mail_activity_data_todo'])
        # Publishing pipeline: log the rejected stage with the reason.
        self._pipeline_log(
            'rejected',
            result=reason or self.rejection_reason or False)

    def action_post(self):
        """ Override action_post to require approval (if policy requires it). """
        if self.policy_id and self.policy_id.state == 'active':
            if self.approval_state not in ('approved', 'draft'):
                raise UserError(_(
                    'This post must be approved before publishing. '
                    'Current status: %(status)s',
                    status=self.approval_state
                ))
        return super().action_post()

    def _check_policy_compliance(self):
        """ Validate post against communication.policy. Returns list of warnings. """
        self.ensure_one()
        warnings = []

        if not self.policy_id or self.policy_id.state != 'active':
            return warnings

        policy = self.policy_id

        # 1. Check prohibited_content
        if policy.prohibited_content and self.message_plain:
            prohibited_words = [
                w.strip().lower()
                for w in policy.prohibited_content.split('\n')
                if w.strip()
            ]
            message_lower = self.message_plain.lower()
            found_words = [w for w in prohibited_words if w in message_lower]
            if found_words:
                warnings.append(_(
                    'Message contains prohibited content: %(words)s',
                    words=', '.join(found_words)
                ))

        # 2. Check posting frequency (if plan_line exists)
        if policy.posting_frequency_max_daily > 0 and self.plan_line_id:
            existing_count = self.search_count([
                ('plan_line_id.plan_id', '=', self.plan_line_id.plan_id.id),
                ('plan_line_id.date', '=', self.plan_line_id.date),
                ('id', '!=', self.id),
            ])
            if existing_count >= policy.posting_frequency_max_daily:
                warnings.append(_(
                    'Maximum daily posts (%(max)s) exceeded for this plan.',
                    max=policy.posting_frequency_max_daily
                ))

        # 3. Hashtag validation — TODO
        # 4. Image analysis via AI — TODO (Phase 3)

        return warnings

    def write(self, vals):
        res = super().write(vals)
        if vals.get('state') == 'posted':
            for post in self:
                if post.plan_line_id:
                    post.plan_line_id._check_line_completion()
        return res

    # --- AI Integration ---

    def action_ai_generate(self):
        """ Generate content with AI. """
        self.ensure_one()
        ai_helper = self.env['social.planner.ai']
        success = ai_helper.generate_post_content(self.id)
        if success:
            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': _('AI Content Generated'),
                    'message': _('Content has been generated and filled into the post.'),
                    'type': 'success',
                    'sticky': False,
                }
            }
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('AI Generation Failed'),
                'message': _('Could not generate content. Make sure an AI agent is configured.'),
                'type': 'warning',
                'sticky': True,
            }
        }

    def action_ai_suggest_hashtags(self):
        """ Suggest hashtags with AI. """
        self.ensure_one()
        ai_helper = self.env['social.planner.ai']
        hashtags = ai_helper.suggest_hashtags(self.id)
        if hashtags:
            current = self.message_plain or ''
            new_message = current + '\n\n' + ' '.join(hashtags)
            self.write({'message': new_message})

    def action_ai_analyze_sentiment(self):
        """ Analyze sentiment for post content. """
        self.ensure_one()
        if not self.message_plain:
            return
        ai_helper = self.env['social.planner.ai']
        result = ai_helper.analyze_sentiment(self.message_plain)
        self.message_post(
            body=_('AI Sentiment Analysis: %(sentiment)s (score: %(score).2f)',
                   sentiment=result['sentiment'], score=result['score']),
            message_type='notification')

    @api.model
    def _cron_publish_recheck(self):
        """ Re-run compliance for posts flagged by a policy version change
        and sweep posts stuck in posting whose live posts are all terminal. """
        posts = self.search([('needs_recheck', '=', True)])
        for post in posts:
            # A post with no reachable policy cannot be re-checked against
            # anything. Clearing the flag without a verdict would record a
            # result for a check that never ran, so the flag stays and the
            # post keeps its stage until a policy becomes available.
            #
            # The flag staying set means this cron sees the post again on
            # every run. Log only on the transition into that state, otherwise
            # a post parked here would accumulate one step record per cron
            # tick forever.
            if not post.policy_id:
                already_deferred = post.pipeline_step_ids.filtered(
                    lambda s: s.stage == 'needs_recheck' and s.state == 'pending')
                if not already_deferred:
                    post._pipeline_log(
                        'needs_recheck', state='pending',
                        result=_('No policy available; re-check deferred.'))
                continue

            warnings = post._check_policy_compliance()
            if warnings:
                previously_passed = (
                    (post.compliance_snapshot or {}).get('verdict') == 'pass')
                post.write({
                    'compliance_recheck_verdict': 'fail',
                    'needs_recheck': False,
                })
                # Distinguish a post that regressed after having passed from
                # one that failed its first check: the regression is the
                # actionable case and must not be conflated with ordinary
                # failure.
                if previously_passed:
                    post._pipeline_log(
                        'compliance_recheck_failed', state='failed',
                        result=_('Policy re-check failed: %s',
                                 '; '.join(warnings)))
                    body = _(
                        'Policy re-check FAILED after the post had already '
                        'passed at version %(version)s: %(warnings)s',
                        version=(post.compliance_snapshot or {}).get(
                            'policy_version'),
                        warnings='; '.join(warnings))
                else:
                    post._pipeline_log(
                        'failed', state='failed',
                        result=_('Policy re-check failed: %s',
                                 '; '.join(warnings)))
                    body = _(
                        'Policy re-check failed: %s', '; '.join(warnings))
                post.message_post(
                    body=body,
                    message_type='notification',
                    subtype_xmlid='mail.mt_comment')
            else:
                post.write({
                    'compliance_recheck_verdict': 'pass',
                    'needs_recheck': False,
                })
                # A distinct stage, so a re-check passing cannot be mistaken
                # for the original compliance check in the audit log.
                post._pipeline_log(
                    'compliance_recheck_passed',
                    result=_('Policy re-check passed at version %s',
                             post.policy_id.version))
        # Sweep: complete posts whose live posts are all terminal (covers
        # permanent job failures that never got a success callback).
        self.search([('state', '=', 'posting')])._check_post_completion()
        return True

    def _recheck_flag_stuck(self):
        """ Posts flagged for re-check that cannot be re-checked at all.

        Surfaces the case where a policy was archived or unlinked while posts
        still referenced it. Those posts keep their flag (see
        _cron_publish_recheck) and would otherwise sit silently forever. """
        return self.search([
            ('needs_recheck', '=', True),
            ('policy_id', '=', False),
        ])
