# -*- coding: utf-8 -*-
# Vertel Sverige AB AGPL-3

{
    'name': 'Social: Marketing',
    'category': 'Marketing/Social Marketing',
    'summary': 'Manage your social marketing',
    'version': '1.3.0',
    'description': """Manage your social marketing """,
    'website': 'https://vertel.se/app/odoo-social',
    'depends': ['web', 'mail', 'link_tracker', 'queue_job'],
    'data': [
        'security/social_marketing_security.xml',
        'security/ir.model.access.csv',
        'data/social_marketing_platform_data.xml',
        'data/ir_cron_data.xml',
        'views/social_marketing_menu_views.xml',
        'views/social_marketing_account_views.xml',
        'views/social_marketing_post_template_views.xml',
        'views/social_image_template_views.xml',
        'views/social_image_render_wizard_views.xml',
        'views/social_data_binding_views.xml',
        'views/social_marketing_post_views.xml',
        'views/res_config_settings_views.xml',
        'views/social_marketing_media_views.xml',
        'views/social_publish_rate_limit_views.xml',
        'views/discuss_channel_view.xml',
        # 'views/utm_campaign_views.xml',
        'views/social_marketing_stream_post_views.xml',
        'views/social_marketing_inbox_views.xml',
        'views/social_marketing_stream_views.xml',
        'views/social_marketing_live_post_views.xml',
        'views/social_marketing_stat_views.xml',

        'views/social_marketing_templates.xml'
    ],
    'demo': [
        'data/social_marketing_demo.xml'
    ],
    'assets': {
        'web.assets_backend': [
            'social_marketing/static/src/lib/fabric_loader.js',
            'social_marketing/static/src/js/fields/*',
            'social_marketing/static/src/js/add_stream_modal.js',
            'social_marketing/static/src/js/images_carousel_dialog.js',
            'social_marketing/static/src/js/post_kanban_view.js',
            'social_marketing/static/src/js/social_marketing_post_formatter_mixin.js',
            'social_marketing/static/src/js/social_marketing_post_preview_field.js',
            'social_marketing/static/src/js/stream_post_comment.js',
            'social_marketing/static/src/js/stream_post_comment_list.js',
            'social_marketing/static/src/js/stream_post_comments.js',
            'social_marketing/static/src/js/stream_post_comments_reply.js',
            'social_marketing/static/src/js/stream_post_kanban_controller.js',
            'social_marketing/static/src/js/stream_post_kanban_dashboard.js',
            'social_marketing/static/src/js/stream_post_kanban_model.js',
            'social_marketing/static/src/js/stream_post_kanban_record.js',
            'social_marketing/static/src/js/stream_post_kanban_refresh_banner.js',
            'social_marketing/static/src/js/stream_post_kanban_renderer.js',
            'social_marketing/static/src/js/stream_post_kanban_view.js',
            'social_marketing/static/src/scss/social.scss',
            'social_marketing/static/src/xml/**/*',
        ],
    },
    'application': True,
    'installable': True,
    'license': 'AGPL-3',
}
